
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS meetings;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS status;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS transaction_status;
DROP TABLE IF EXISTS users;


